'''
Authors: Sherwood Richers; Claude AI
NOTE: This file was generated by Claude AI. It was tested against the Python rhea models,
but the logic was not human-vetted.

Copyright: GPLv3 (see LICENSE file)

Export a trained checkpoint to the flat .rhea binary that the standalone evaluator in this
directory reads, so that inference needs neither LibTorch nor e3nn.

Lives here rather than in model_training/ because the file format is this directory's
concern: rhea_loader.hpp has to agree with it byte for byte.

Nothing about e3nn's normalization conventions is re-derived here: the irreps lists, the
per-instruction path weights and weight layouts, and the Wigner 3j tables are all read off
the constructed modules, which is what keeps this correct as e3nn changes.

The file format follows e3nn's own conventions - its instruction tables, path weights and
irreps layout - so that a checkpoint round-trips without reinterpretation. e3nn is MIT
licensed; see THIRD_PARTY_LICENSES at the repository root.

The architecture is recovered from the checkpoint by reexport.infer_parms, so a new
width or depth exports without being told. The activations are the one thing a
checkpoint cannot carry (they have no parameters), so they are supplied and then
verified, exactly as reexport.py does.
'''
import argparse
import os
import struct
import sys

import numpy as np
import torch
import e3nn.o3
import e3nn.nn

# The architecture and the weight layout are read off a live model, so this needs the
# training code even though it lives with the consumer that reads what it writes. Add the
# path here rather than requiring a cwd, the way ml_read_data.py does for data/.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "..", "model_training"))
from ml_neuralnet import NeuralNetwork, PETP_Linear, PETP_Quadratic
from reexport import infer_parms, resolve_activation, ACTIVATIONS

MAGIC = b"RHEAKOK1"

# activation identifiers shared with the C++ side
ACT_ID = {"identity":0, "silu":1, "sigmoid":2, "tanh":3, "relu":4, "gelu":5}

# tensor product connection modes the exporter understands
MODE_ID = {"uvw":0, "uuu":1}

TP_LINEAR    = 0
TP_QUADRATIC = 1

#=========================#
# little-endian primitives #
#=========================#
def w_i32(buf, *vals):
    for v in vals:
        buf.append(struct.pack("<i", int(v)))

def w_f32(buf, *vals):
    for v in vals:
        buf.append(struct.pack("<f", float(v)))

def w_farray(buf, arr):
    a = np.ascontiguousarray(np.asarray(arr, dtype="<f4"))
    w_i32(buf, a.size)
    buf.append(a.tobytes())

def w_irreps(buf, irreps):
    # [n, (mul,l,p) * n]
    irreps = e3nn.o3.Irreps(irreps)
    w_i32(buf, len(irreps))
    for mul, ir in irreps:
        w_i32(buf, mul, ir.l, ir.p)

#==================================#
# tensor products and linear layers #
#==================================#
def live_instructions(module):
    '''The instructions e3nn actually generates code for.

    Both _codegen_linear and codegen_tensor_product_left_right drop instructions with a
    zero in path_shape before laying out the weight vector, so an exporter that keeps
    them would assign every following instruction the wrong weight offset.
    '''
    return [ins for ins in module.instructions if 0 not in ins.path_shape]

def w_tensor_product(buf, tp, w3j_triples):
    instructions = live_instructions(tp)

    w_irreps(buf, tp.irreps_in1)
    w_irreps(buf, tp.irreps_in2)
    w_irreps(buf, tp.irreps_out)

    w_i32(buf, len(instructions))
    offset = 0
    for ins in instructions:
        assert ins.connection_mode in MODE_ID, \
            f"unsupported connection mode {ins.connection_mode}"
        l1 = tp.irreps_in1[ins.i_in1].ir.l
        l2 = tp.irreps_in2[ins.i_in2].ir.l
        l3 = tp.irreps_out[ins.i_out].ir.l
        w3j_triples.add((l1,l2,l3))

        # path_shape is (u,v,w) for uvw and (u,) for uuu; pad so the record is fixed width
        shape = list(ins.path_shape) + [1,1,1]
        w_i32(buf, ins.i_in1, ins.i_in2, ins.i_out,
                   MODE_ID[ins.connection_mode], int(ins.has_weight),
                   offset if ins.has_weight else -1,
                   shape[0], shape[1], shape[2])
        w_f32(buf, ins.path_weight)
        if ins.has_weight:
            offset += int(np.prod(ins.path_shape))

    assert offset == tp.weight_numel, (offset, tp.weight_numel)
    weight = tp.weight.detach().cpu().numpy().ravel() if tp.weight_numel > 0 else np.zeros(0)
    w_farray(buf, weight)

def w_linear(buf, lin):
    instructions = live_instructions(lin)
    assert all(ins.i_in >= 0 for ins in instructions), \
        "biases are not supported by the exporter; ml_neuralnet builds o3.Linear without them"

    w_irreps(buf, lin.irreps_in)
    w_irreps(buf, lin.irreps_out)

    w_i32(buf, len(instructions))
    offset = 0
    for ins in instructions:
        w_i32(buf, ins.i_in, ins.i_out, offset,
                   ins.path_shape[0], ins.path_shape[1])
        w_f32(buf, ins.path_weight)
        offset += int(np.prod(ins.path_shape))

    assert offset == lin.weight_numel, (offset, lin.weight_numel)
    w_farray(buf, lin.weight.detach().cpu().numpy().ravel())

#========#
# blocks #
#========#
def act_scale(activation):
    '''The constant e3nn.nn.Activation folds into every activation.

    Activation wraps each act in normalize2mom, which rescales it to unit second moment
    on a standard normal (silu picks up ~1.68). It is a property of the activation, not
    a trained value, so it appears nowhere in the state dict and has to be carried here.
    normalize2mom skips the multiply outright when the constant is within 1e-4 of one,
    so that case is written as exactly one rather than as the estimate.
    '''
    scales = [1.0 if a._is_id else float(a.cst) for a in activation.acts]
    assert all(a is not None for a in activation.acts), "an activation slot is empty"
    assert len(set(scales)) == 1, f"mixed activation normalizations {scales}"
    return scales[0]

def w_block(buf, block, act_scalar, act_gate, w3j_triples):
    '''One PE_ResidualGatedBlock.

    The block output is skip(x) + alpha*gate(tp(x)). The gate and skip paths are written
    with their own irreps rather than a single block output layout, because ml_neuralnet
    does not require them to agree: Gate always emits scalars first, while o3.Linear
    preserves whatever order irreps_out was declared in. The two are added componentwise
    regardless, so recording each separately reproduces the checkpoint exactly.
    '''
    tp = block.tp
    is_quadratic = isinstance(tp, PETP_Quadratic)
    assert is_quadratic or isinstance(tp, PETP_Linear), type(tp)

    w_i32(buf, TP_QUADRATIC if is_quadratic else TP_LINEAR)
    w_f32(buf, float(block.alpha.detach()))

    if is_quadratic:
        # NormActivation: norms = Norm(x) (squared), clamp, sqrt, tanh(n)/n, then multiply
        na = tp.norm_act
        assert na.normalize and na._eps_squared > 0, "unexpected NormActivation configuration"
        w_f32(buf, na._eps_squared)
        w_tensor_product(buf, na.norm.tp,            w3j_triples)
        w_tensor_product(buf, na.scalar_multiplier,  w3j_triples)
        for name in ["tp_self","tp_flavor","tp_nunubar","tp_all"]:
            w_tensor_product(buf, getattr(tp, name), w3j_triples)
    else:
        for name in ["lin_self","lin_flavor","lin_nunubar","lin_all"]:
            w_linear(buf, getattr(tp, name))

    # gate: either e3nn.nn.Gate (scalars + gates + gated) or a plain Activation on scalars
    gate = block.gate
    is_gate = isinstance(gate, e3nn.nn.Gate)
    w_i32(buf, int(is_gate))
    if is_gate:
        w_irreps(buf, gate.irreps_scalars)
        w_irreps(buf, gate.irreps_gates)
        w_irreps(buf, gate.irreps_gated)
        w_i32(buf, ACT_ID[act_scalar], ACT_ID[act_gate])
        w_f32(buf, act_scale(gate.act_scalars), act_scale(gate.act_gates))
        w_tensor_product(buf, gate.mul, w3j_triples)
    else:
        w_irreps(buf, gate.irreps_in)
        w_i32(buf, ACT_ID[act_scalar])
        w_f32(buf, act_scale(gate))

    # skip: identity when the block preserves its irreps, a projection otherwise
    has_skip = isinstance(block.skip, e3nn.o3.Linear)
    w_i32(buf, int(has_skip))
    if has_skip:
        w_linear(buf, block.skip)

def f4_output_permutation(model):
    '''Which xyzt slot each output of the F4 head belongs to.

    predict_all adds the head's output to F4, whose last axis is [x,y,z,t], but the head's
    own order is whatever Gate produced - scalars first since 87cd6a8, vector first before
    that. Recording the mapping rather than assuming it keeps the C++ side correct across
    that change and any future one.
    '''
    perm = []
    for mul, ir in model.TP_activation_stack_F4[-1].irreps_out:
        for _ in range(mul):
            if   ir.l == 0: perm += [3]
            elif ir.l == 1: perm += [0,1,2]
            else: raise SystemExit(f"the F4 head emits {ir}, which has no place in a four-vector")
    assert sorted(perm) == [0,1,2,3], f"the F4 head does not produce one four-vector: {perm}"
    return perm


#=======#
# model #
#=======#
def w_model(model, act_scalar, act_gate):
    buf = []
    w3j_triples = set()

    body = []
    w_irreps(body, model.irreps_in)
    for name in ["TP_activation_stack_shared",
                 "TP_activation_stack_growthrate",
                 "TP_activation_stack_F4"]:
        stack = getattr(model, name)
        w_i32(body, len(stack))
        for block in stack:
            w_block(body, block, act_scalar, act_gate, w3j_triples)

    # header
    buf.append(MAGIC)
    w_i32(buf, int(model.NF),
               int(model.conserve_lepton_number),
               int(model.average_heavies_in_final_state))

    # lebedev quadrature, stored [3, npoints] as box3d supplies it
    pts = model.lebedev_pts.detach().cpu().numpy()
    w_i32(buf, pts.shape[1])
    w_farray(buf, pts.ravel())
    w_farray(buf, model.lebedev_weights.detach().cpu().numpy().ravel())

    # Wigner 3j tables, sparse. These are constants of the representation theory, not
    # trained values, but shipping them avoids reimplementing wigner_3j in C++.
    triples = sorted(w3j_triples)
    w_i32(buf, len(triples))
    for (l1,l2,l3) in triples:
        t = e3nn.o3.wigner_3j(l1,l2,l3).detach().cpu().numpy()
        nz = np.argwhere(t != 0.0)
        w_i32(buf, l1, l2, l3, len(nz))
        for (i,j,k) in nz:
            w_i32(buf, i, j, k)
            w_f32(buf, t[i,j,k])

    buf.extend(body)

    # where each output of the F4 head lands in [x,y,z,t]
    w_i32(buf, *f4_output_permutation(model))
    return b"".join(buf)

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("checkpoint", help="existing .pt saved by save_model")
    ap.add_argument("outfile",    help="output .rhea file")
    ap.add_argument("--scalar-activation",    default="silu")
    ap.add_argument("--nonscalar-activation", default="sigmoid")
    args = ap.parse_args()

    for name in [args.scalar_activation, args.nonscalar_activation]:
        assert name in ACT_ID, f"activation {name!r} has no C++ counterpart; known: {sorted(ACT_ID)}"

    old = torch.jit.load(args.checkpoint, map_location="cpu")
    old.eval()

    parms = infer_parms(old,
                        resolve_activation(args.scalar_activation),
                        resolve_activation(args.nonscalar_activation))
    model = NeuralNetwork(parms)
    missing, unexpected = model.load_state_dict(old.state_dict(), strict=False)
    missing    = [k for k in missing    if "w3j" not in k]
    unexpected = [k for k in unexpected if "w3j" not in k]
    assert not missing and not unexpected, (missing[:5], unexpected[:5])
    model.eval()

    # the activations carry no parameters, so a wrong one loads silently
    torch.manual_seed(0)
    x = torch.randn(64, 2, int(old.NF), model.irreps_in.dim)
    with torch.inference_mode():
        (a_F4, a_gr), (b_F4, b_gr) = old.forward(x), model.forward(x)
    err = max(float((a_F4-b_F4).abs().max()), float((a_gr-b_gr).abs().max()))
    print(f"#  rebuilt network matches the checkpoint to {err:.3e}")
    assert err == 0.0, "the rebuilt network is not the one that was trained (wrong activation?)"

    blob = w_model(model, args.scalar_activation, args.nonscalar_activation)
    with open(args.outfile, "wb") as f:
        f.write(blob)
    print(f"#  wrote {args.outfile}  ({len(blob)} bytes)")

if __name__ == "__main__":
    main()
