/*
Authors: Sherwood Richers; Claude AI
NOTE: This file was generated by Claude AI and is tested against the python version of e3nn.
However, the actual logic was not human-vetted.

License: GPLv3 (see LICENSE file)

Host-side reader for the .rhea files written by export_rhea.py in this directory. It
resolves every irrep slice into flat offsets at load time so that the evaluator in
rhea_model.hpp never has to walk an irreps list, and concatenates every weight vector
into one array. Nothing here runs on a device; RheaModelHost::tables() hands the
evaluator plain pointers into these vectors.

The tensor product instruction tables, path weight conventions and irreps layout
implemented here follow e3nn (MIT, (c) 2020 The Regents of the University of California
through Lawrence Berkeley National Laboratory, EPFL, Free University of Berlin, and
Kostiantyn Lapchevskyi). No e3nn source is reproduced; see THIRD_PARTY_LICENSES at the
repository root for what is borrowed and for the MIT notice.
*/
#ifndef RHEA_LOADER_HPP
#define RHEA_LOADER_HPP

#include "rhea_model.hpp"

struct RheaIrrepEntry { int mul, l, p, dim, off; };

class RheaModelHost {
  public:
    std::vector<RheaW3J>    w3j;
    std::vector<RheaTPIns>  tp_ins;
    std::vector<RheaTP>     tps;
    std::vector<RheaLinIns> lin_ins;
    std::vector<RheaLin>    lins;
    std::vector<RheaBlock>  blocks;
    std::vector<float>      w, pts, wts;
    RheaTables              T;

    RheaModelHost(const std::string& filename){ load(filename); }

    RheaTables tables() const {
        RheaTables t = T;
        t.w3j     = w3j.data();
        t.tp_ins  = tp_ins.data();
        t.tps     = tps.data();
        t.lin_ins = lin_ins.data();
        t.lins    = lins.data();
        t.blocks  = blocks.data();
        t.w       = w.data();
        t.pts     = pts.data();
        t.wts     = wts.data();
        return t;
    }

  private:
    std::vector<char> d;
    size_t            p = 0;
    // (l1,l2,l3) -> offset into w3j, so a table shared by many paths is stored once
    std::vector<int>  w3j_key, w3j_off, w3j_cnt;

    int   i32(){ int v;   std::memcpy(&v, d.data()+p, 4); p += 4; return v; }
    float f32(){ float v; std::memcpy(&v, d.data()+p, 4); p += 4; return v; }

    std::vector<float> farray(){
        const int n = i32();
        std::vector<float> a(n);
        if(n) std::memcpy(a.data(), d.data()+p, 4*(size_t)n);
        p += 4*(size_t)n;
        return a;
    }

    std::vector<RheaIrrepEntry> irreps(){
        const int n = i32();
        std::vector<RheaIrrepEntry> e(n);
        int off = 0;
        for(int i=0; i<n; i++){
            e[i].mul = i32(); e[i].l = i32(); e[i].p = i32();
            e[i].dim = e[i].mul*(2*e[i].l+1);
            e[i].off = off;
            off += e[i].dim;
        }
        return e;
    }
    static int dim_of(const std::vector<RheaIrrepEntry>& e){
        return e.empty() ? 0 : e.back().off + e.back().dim;
    }

    int find_w3j(int l1, int l2, int l3, int& nnz) const {
        const int key = (l1*64 + l2)*64 + l3;
        for(size_t i=0; i<w3j_key.size(); i++)
            if(w3j_key[i] == key){ nnz = w3j_cnt[i]; return w3j_off[i]; }
        throw std::runtime_error("missing Wigner 3j table");
    }

    int read_tp(){
        auto in1 = irreps(), in2 = irreps(), out = irreps();
        RheaTP tp;
        tp.ins_off = (int)tp_ins.size();
        tp.n_ins   = i32();
        tp.dim_out = dim_of(out);
        for(int n=0; n<tp.n_ins; n++){
            RheaTPIns ins;
            const int i1 = i32(), i2 = i32(), io = i32();
            ins.mode = i32(); ins.has_w = i32(); ins.woff = i32();
            ins.u = i32(); ins.v = i32(); ins.w = i32();
            ins.pw = f32();
            ins.w3j_off = find_w3j(in1[i1].l, in2[i2].l, out[io].l, ins.w3j_nnz);
            ins.in1_off = in1[i1].off; ins.in1_d = 2*in1[i1].l + 1;
            ins.in2_off = in2[i2].off; ins.in2_d = 2*in2[i2].l + 1;
            ins.out_off = out[io].off; ins.out_d = 2*out[io].l + 1;
            // a uuu path carries only a multiplicity in path_shape; the loops want it in u
            if(ins.mode == 1) ins.u = in1[i1].mul;
            tp_ins.push_back(ins);

            if(ins.out_d > RHEA_MAX_IRREP_DIM || ins.in1_d > RHEA_MAX_IRREP_DIM
                                              || ins.in2_d > RHEA_MAX_IRREP_DIM)
                throw std::runtime_error("an irrep exceeds RHEA_MAX_IRREP_DIM; rebuild with a larger value");
        }
        auto ws = farray();
        tp.w_off = (int)w.size();
        w.insert(w.end(), ws.begin(), ws.end());
        tps.push_back(tp);
        return (int)tps.size() - 1;
    }

    int read_linear(){
        auto in = irreps(), out = irreps();
        RheaLin lin;
        lin.ins_off = (int)lin_ins.size();
        lin.n_ins   = i32();
        lin.dim_out = dim_of(out);
        for(int n=0; n<lin.n_ins; n++){
            RheaLinIns ins;
            const int ii = i32(), io = i32();
            ins.woff = i32(); ins.u = i32(); ins.w = i32(); ins.pw = f32();
            ins.in_off  = in[ii].off;  ins.in_d  = 2*in[ii].l + 1;
            ins.out_off = out[io].off; ins.out_d = 2*out[io].l + 1;
            lin_ins.push_back(ins);
        }
        auto ws = farray();
        lin.w_off = (int)w.size();
        w.insert(w.end(), ws.begin(), ws.end());
        lins.push_back(lin);
        return (int)lins.size() - 1;
    }

    void read_block(int dim_in){
        RheaBlock b{};
        b.dim_in = dim_in;
        b.kind   = i32();
        b.alpha  = f32();
        if(b.kind == 1){
            b.eps2       = f32();
            b.tp_norm    = read_tp();
            b.tp_normmul = read_tp();
            for(int i=0; i<4; i++) b.branch[i] = read_tp();
            b.dim_tp = tps[b.branch[0]].dim_out;
        } else {
            for(int i=0; i<4; i++) b.branch[i] = read_linear();
            b.dim_tp = lins[b.branch[0]].dim_out;
        }

        b.is_gate = i32();
        if(b.is_gate){
            b.dim_scalars = dim_of(irreps());
            b.dim_gates   = dim_of(irreps());
            b.dim_gated   = dim_of(irreps());
            b.act_scalar  = i32(); b.act_gate = i32();
            b.scale_scalar= f32(); b.scale_gate = f32();
            b.tp_mul      = read_tp();
            b.dim_out     = b.dim_scalars + b.dim_gated;
        } else {
            b.dim_scalars = dim_of(irreps());
            b.dim_gates   = 0; b.dim_gated = 0;
            b.act_scalar  = i32();
            b.scale_scalar= f32();
            b.dim_out     = b.dim_scalars;
        }

        b.has_skip = i32();
        if(b.has_skip) b.lin_skip = read_linear();

        if(b.dim_in  > T.dim_max)    T.dim_max    = b.dim_in;
        if(b.dim_out > T.dim_max)    T.dim_max    = b.dim_out;
        if(b.dim_tp  > T.dim_tp_max) T.dim_tp_max = b.dim_tp;
        blocks.push_back(b);
    }

    void load(const std::string& filename){
        std::ifstream f(filename, std::ios::binary);
        if(!f) throw std::runtime_error("cannot open " + filename);
        d.assign(std::istreambuf_iterator<char>(f), std::istreambuf_iterator<char>());
        if(d.size() < 8 || std::memcmp(d.data(), "RHEAKOK1", 8) != 0)
            throw std::runtime_error(filename + " is not a rhea model file");
        p = 8;

        std::memset(&T, 0, sizeof(T));
        T.NF = i32();
        // the flavor-pair structure in rhea_box3d and the incident-rate inputs in
        // rhea_predict_cell are written for the three pairs of three flavors
        if(T.NF != 3) throw std::runtime_error("only NF=3 is supported");
        T.conserve_lepton_number = i32();
        T.average_heavies        = i32();
        T.nnodes = 2*T.NF;

        T.npts = i32();
        pts = farray();
        wts = farray();

        const int ntriples = i32();
        for(int t=0; t<ntriples; t++){
            const int l1 = i32(), l2 = i32(), l3 = i32(), nnz = i32();
            w3j_key.push_back((l1*64 + l2)*64 + l3);
            w3j_off.push_back((int)w3j.size());
            w3j_cnt.push_back(nnz);
            for(int z=0; z<nnz; z++){
                RheaW3J e; e.i = i32(); e.j = i32(); e.k = i32(); e.v = f32();
                w3j.push_back(e);
            }
        }

        T.dim_in = dim_of(irreps());
        T.dim_max = T.dim_in;

        // the trunk feeds both heads, so both start at the trunk's output width
        int dim = T.dim_in, dim_trunk = 0;
        T.stack_off[0] = 0;
        for(int st=0; st<3; st++){
            const int n = i32();
            if(st > 0) dim = dim_trunk;
            for(int i=0; i<n; i++){ read_block(dim); dim = blocks.back().dim_out; }
            if(st == 0) dim_trunk = dim;
            T.stack_off[st+1] = (int)blocks.size();
        }
        // where each output of the F4 head lands in [x,y,z,t]: Gate emits scalars first,
        // so the head's own order is not the four-vector's
        for(int i=0; i<4; i++) T.f4_perm[i] = i32();
        int seen = 0;
        for(int i=0; i<4; i++) seen |= 1 << T.f4_perm[i];
        if(seen != 0xF) throw std::runtime_error("the F4 head permutation is not a permutation");

        if(p != d.size()) throw std::runtime_error("trailing bytes in .rhea file");

        // box3d needs g[2,NF,npts] and one survival probability per flavor pair
        const int npair = T.NF*(T.NF-1)/2;
        const int box   = T.nnodes*T.npts + npair*T.npts + 64;
        const int net   = 3*T.nnodes*T.dim_max + 2*T.dim_max + T.NF*T.dim_max + T.dim_max
                        + 3*T.dim_max + 2*T.dim_tp_max;
        T.scratch_floats = (net > box) ? net : box;
        if(T.scratch_floats > RHEA_MAX_SCRATCH)
            throw std::runtime_error("this model needs " + std::to_string(T.scratch_floats) +
                                     " floats of scratch; rebuild with -DRHEA_MAX_SCRATCH=" +
                                     std::to_string(T.scratch_floats));
    }
};

#endif
